### ISSUE TITLE
Find a way to manually unify/disambiguate authors

### ISSUE THREAD

**Issue by bockthom** [se-passau/coronet#178]
### Description

_Disclaimer:_ This is a general issue which is not directly related to `coronet`, but could be somehow addressed via a workaround in `coronet` or in `codeface-extraction`, for example.

In general, Codeface's disambiguation algorithm for persons (name, e-mail pairs) is not perfect. On the one hand, as Codeface is overwriting persons' names in the database instead of storing all the names associated with the corresponding e-mail address. On the other hand, sometimes a person uses different name e-mail pairs which cannot be automatically matched, but only manually matched when looking at the author data. For such cases, we should provide a possibility to manually unify authors.

### Motivation

There are lots of authors which use different name-email pairs like the following:

`Forename Surname <user@organization1.com>`
`username <forename@surename.com>`

In such a situation, we cannot automatically determine that these two persons are identical, as they don't use mixed names or e-mail address combinations. However, when personally looking at those names, usernames, e-mail addresses and their combinations, it often is very obvious to a human eye that those persons must be identical. This often holds for central developers of open-source projects, using lots of different e-mail addresses and (user)names. Hence, this could be important when looking at the centrality values of such authors in the developer networks.

I stumbled over this problem for quite a while in the data of many projects. As long as we have no means to automatically handle this, it would be helpful to have a manual workaround provided for that. Such a workaround could contain an additional file specifying sets of author names which should be treated as one author (identified through manual inspection of the author data).

### Ideas for the Implementation

There are two possibilities on how to achieve that workaround:

(1) **Pre-coronet workaround:** Write script which adjusts all the .list files (maybe as an enhancement to the `codeface-extraction`. That is, in such a script, the file containing the specified author sets need to be read in, all the .list files of that project need to be read in, adjusted an re-written again. In such a case, the already adjusted .list files would be read in by coronet without any additional treatments.

(2) **In-coronet workaround:** Coronet needs to read in the file containing the specified author sets. When reading (or processing) several data, coronet needs to replace author's names according to those specified author sets.

### Additional Information

I just added this issue now as I stumbled over this problem again while coincidentally investigating the author data of the coronet project itself :wink: (5 out of the 13 authors occur with two different authors in the author data after running Codeface and GitHubWrapper...)
As I already have thought about this problem some months ago (which is not an issue in coronet, but could result in a workaround in coronet), I have decided to document this issue and the corresponding workarounds here, just to not forget about it...

**Comment by hechtlC** [comment]
Thanks for the thorough documentation of this issue @bockthom.

Personally, I would prefer the pre-coronet workaround as it seems more intuitive that we adjust this where we prepare the data for coronet. But this is just a personal preference.

**Comment by clhunsen** [comment]
> Personally, I would prefer the pre-coronet workaround as it seems more intuitive that we adjust this where we prepare the data for coronet. But this is just a personal preference.

I agree with @hechtlC: It may be better to have as few preprocessing steps as possible in coronet, which is one of the reasons why we have the codeface-extraction project in the first place.
